# -*- coding: utf-8 -*-
"""code 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsEeaJUb_iL1CdEptQIn-6b0FBZ_BtFz
"""

import tkinter as tk
from tkinter import messagebox

# Create the main application window
root = tk.Tk()
root.title("Grand Prix Ticketing System")  # Set the window title
root.geometry("500x400")  # Set the size of the window (width x height)

# -------------------------------
# Functions to handle button actions
# -------------------------------

def login():
    """
    Simulates user login using the entered username and password.
    """
    username = username_entry.get()
    password = password_entry.get()

    # Check if both fields are filled
    if username and password:
        # Placeholder for login validation logic
        messagebox.showinfo("Login Success", f"Welcome {username}!")
    else:
        # Show error if either field is empty
        messagebox.showerror("Login Failed", "Please enter username and password")

def create_account():
    """
    Placeholder function for account creation.
    """
    # In future, open a new window for user registration
    messagebox.showinfo("Account", "Account creation form coming soon!")

def view_tickets():
    """
    Display available ticket options to the user.
    """
    tickets_info = (
        "Ticket options:\n"
        "1. Single Race\n"
        "2. Weekend Pass\n"
        "3. Season Membership\n"
        "4. Group Discount"
    )
    messagebox.showinfo("Tickets", tickets_info)

def admin_dashboard():
    """
    Placeholder function for the admin dashboard.
    """
    admin_info = (
        "Admin Dashboard:\n"
        "- Track sales\n"
        "- Modify discounts\n"
        "- Manage inventory"
    )
    messagebox.showinfo("Admin Dashboard", admin_info)

def exit_app():
    """
    Exit the application.
    """
    root.destroy()

# -------------------------------
# UI Widgets (Labels, Entries, Buttons)
# -------------------------------

# Username label and text entry
username_label = tk.Label(root, text="Username:")
username_label.pack()
username_entry = tk.Entry(root)
username_entry.pack()

# Password label and text entry (hidden with "*")
password_label = tk.Label(root, text="Password:")
password_label.pack()
password_entry = tk.Entry(root, show="*")
password_entry.pack()

# Login button
login_button = tk.Button(root, text="Login", command=login)
login_button.pack(pady=5)  # Add vertical spacing

# Create account button
create_button = tk.Button(root, text="Create Account", command=create_account)
create_button.pack(pady=5)

# View tickets button
view_button = tk.Button(root, text="View Tickets", command=view_tickets)
view_button.pack(pady=5)

# Admin dashboard button
admin_button = tk.Button(root, text="Admin Dashboard", command=admin_dashboard)
admin_button.pack(pady=5)

# Exit button
exit_button = tk.Button(root, text="Exit", command=exit_app)
exit_button.pack(pady=5)

# -------------------------------
# Start the GUI loop (keeps the window running)
# -------------------------------
root.mainloop()